/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_reverse_JNIDemo */

#ifndef _Included_com_example_reverse_JNIDemo
#define _Included_com_example_reverse_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_reverse_JNIDemo
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_reverse_JNIDemo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
